//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SdfTools.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SdfTools.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NewSchema.
        /// </summary>
        public static string Default_NewSchemaName {
            get {
                return ResourceManager.GetString("Default_NewSchemaName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geo Data Files (*.shp;*.sdf;*.sqlite)|*.shp;*.sdf;*.sqlite.
        /// </summary>
        public static string FileDialog_GeoDataFilter {
            get {
                return ResourceManager.GetString("FileDialog_GeoDataFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schema Files (*.xml;*.json)|*.xml;*.json|All Files (*.*)|*.*.
        /// </summary>
        public static string FileDialog_SchemaFilter {
            get {
                return ResourceManager.GetString("FileDialog_SchemaFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attribute Mapping.
        /// </summary>
        public static string MainWindow_AttributeMapping {
            get {
                return ResourceManager.GetString("MainWindow_AttributeMapping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Schema.
        /// </summary>
        public static string MainWindow_EditSchema {
            get {
                return ResourceManager.GetString("MainWindow_EditSchema", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected Schema:.
        /// </summary>
        public static string MainWindow_SelectedSchema {
            get {
                return ResourceManager.GetString("MainWindow_SelectedSchema", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select File.
        /// </summary>
        public static string MainWindow_SelectFileButton {
            get {
                return ResourceManager.GetString("MainWindow_SelectFileButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Schema.
        /// </summary>
        public static string MainWindow_SelectSchemaButton {
            get {
                return ResourceManager.GetString("MainWindow_SelectSchemaButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source Attribute.
        /// </summary>
        public static string MainWindow_SourceAttribute {
            get {
                return ResourceManager.GetString("MainWindow_SourceAttribute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source File:.
        /// </summary>
        public static string MainWindow_SourceFile {
            get {
                return ResourceManager.GetString("MainWindow_SourceFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Conversion.
        /// </summary>
        public static string MainWindow_StartConversion {
            get {
                return ResourceManager.GetString("MainWindow_StartConversion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Target Attribute.
        /// </summary>
        public static string MainWindow_TargetAttribute {
            get {
                return ResourceManager.GetString("MainWindow_TargetAttribute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GeoDataConverter.
        /// </summary>
        public static string MainWindow_Title {
            get {
                return ResourceManager.GetString("MainWindow_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Attribute:.
        /// </summary>
        public static string SchemaEditor_AddAttribute {
            get {
                return ResourceManager.GetString("SchemaEditor_AddAttribute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string SchemaEditor_AddButton {
            get {
                return ResourceManager.GetString("SchemaEditor_AddButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string SchemaEditor_DeleteButton {
            get {
                return ResourceManager.GetString("SchemaEditor_DeleteButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schema Name:.
        /// </summary>
        public static string SchemaEditor_SchemaName {
            get {
                return ResourceManager.GetString("SchemaEditor_SchemaName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schema Editor.
        /// </summary>
        public static string SchemaEditor_Title {
            get {
                return ResourceManager.GetString("SchemaEditor_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validate Schema.
        /// </summary>
        public static string SchemaEditor_ValidateSchema {
            get {
                return ResourceManager.GetString("SchemaEditor_ValidateSchema", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An attribute with this name already exists..
        /// </summary>
        public static string SchemaService_AttributeAlreadyExists {
            get {
                return ResourceManager.GetString("SchemaService_AttributeAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplicate attributes: {0}.
        /// </summary>
        public static string SchemaService_DuplicateAttributes {
            get {
                return ResourceManager.GetString("SchemaService_DuplicateAttributes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schema is valid..
        /// </summary>
        public static string SchemaService_SchemaValid {
            get {
                return ResourceManager.GetString("SchemaService_SchemaValid", resourceCulture);
            }
        }
    }
}
